name: CI/CD Pipeline (Backend + Docker)

on:
  push:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        cd Testing/Backend
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        cd Testing/Backend
        pytest

    - name: Build Docker image
      run: |
        cd Testing/Backend
        docker build -t backend-test-app .

    - name: Show Docker images
      run: docker images